# categories.py

CATEGORIES = {
    # 1–15
    "Audio": ["Headphones", "Speakers", "Soundbars", "Home Audio Systems", "Car Audio"],
    "TV & Video": ["LED TVs", "OLED TVs", "Projectors", "Streaming Devices", "Blu-ray/DVD Players"],
    "Computers": ["Laptops", "Desktops", "Monitors", "Computer Accessories", "Networking Equipment"],
    "Cameras and camcorders": ["Digital Cameras", "DSLR Cameras", "Mirrorless Cameras", "Camcorders", "Camera Accessories"],
    "Cell phones": ["Smartphones", "Feature Phones", "Phone Accessories", "Power Banks", "Wearable Connectivity"],
    "Music, Movies and Audio Books": ["Music CDs", "Movie DVDs", "Blu-ray Movies", "Audio Books", "Digital Media Cards"],
    "Games and Toys": ["Console Games", "Board Games", "PC Games", "Action Figures", "Toys & Learning Kits"],
    "Home Appliances": ["Refrigerators", "Washing Machines", "Air Conditioners", "Microwave Ovens", "Vacuum Cleaners"],
    "Wearables": ["Smartwatches", "Fitness Bands", "VR Headsets", "Smart Glasses", "Health Trackers"],
    "Smart Home": ["Smart Lights", "Smart Plugs", "Smart Cameras", "Smart Thermostats", "Voice Assistants"],
    "Office Supplies": ["Printers", "Scanners", "Office Furniture", "Writing Supplies", "Storage & Organization"],
    "Furniture": ["Sofas", "Beds", "Chairs", "Tables", "Storage Units"],
    "Kitchen & Dining": ["Cookware", "Tableware", "Small Kitchen Appliances", "Storage Containers", "Cutlery"],
    "Personal Care": ["Grooming Devices", "Hair Care Tools", "Oral Care", "Massage Devices", "Beauty Tools"],
    "Sports & Outdoors": ["Fitness Equipment", "Outdoor Gear", "Sports Apparel", "Cycling", "Camping Equipment"],

    # # 16–100 (new categories)
    # "Automotive": ["Car Accessories", "Car Electronics", "Car Care", "Motorcycle Gear", "Tires & Wheels"],
    # "Home Improvement": ["Power Tools", "Hand Tools", "Lighting Fixtures", "Plumbing", "Electrical Supplies"],
    # "Pet Supplies": ["Pet Food", "Pet Toys", "Pet Grooming", "Aquatic Supplies", "Pet Beds"],
    # "Baby Products": ["Baby Clothing", "Baby Gear", "Feeding", "Bathing", "Nursery Furniture"],
    # "Books": ["Fiction", "Non-Fiction", "Children's Books", "Educational", "Comics & Graphic Novels"],
    # "Fashion": ["Men's Clothing", "Women's Clothing", "Footwear", "Accessories", "Bags & Luggage"],
    # "Jewelry & Watches": ["Watches", "Necklaces", "Bracelets", "Earrings", "Rings"],
    # "Garden & Outdoor": ["Gardening Tools", "Plants & Seeds", "Outdoor Furniture", "Grills & Smokers", "Garden Decor"],
    # "Tools & Industrial": ["Measurement Tools", "Safety Equipment", "Construction Tools", "Welding Tools", "Machinery Accessories"],
    # "Beauty": ["Makeup", "Skincare", "Hair Care", "Perfumes", "Nail Care"],
    # "Health & Wellness": ["Supplements", "Medical Devices", "Health Monitors", "Orthopedic Support", "Wellness Kits"],
    # "Groceries": ["Snacks", "Beverages", "Canned Goods", "Spices", "Dry Foods"],
    # "Cleaning Supplies": ["Surface Cleaners", "Detergents", "Disinfectants", "Cleaning Tools", "Floor Cleaners"],
    # "Home Decor": ["Wall Art", "Lamps", "Curtains", "Decorative Pieces", "Mirrors"],
    # "Bedding": ["Bedsheets", "Blankets", "Pillows", "Mattress Protectors", "Comforters"],
    # "Footwear": ["Sports Shoes", "Formal Shoes", "Casual Shoes", "Sandals", "Boots"],
    # "Luggage": ["Suitcases", "Backpacks", "Duffel Bags", "Travel Accessories", "Laptop Bags"],
    # "Crafts & DIY": ["Art Supplies", "DIY Kits", "Craft Materials", "Sewing Tools", "Painting Accessories"],
    # "Musical Instruments": ["Guitars", "Keyboards", "Drums", "Microphones", "Studio Accessories"],
    # "Security & Surveillance": ["CCTV Cameras", "Alarm Systems", "Motion Sensors", "Smart Locks", "Doorbells"],
    # "Lighting": ["LED Bulbs", "Ceiling Lights", "Outdoor Lights", "Smart Lights", "Decorative Lamps"],
    # "Pharmacy": ["OTC Medicines", "First Aid", "Pain Relief", "Allergy Care", "Digestive Care"],
    # "Party Supplies": ["Party Decor", "Balloons", "Gift Wrap", "Party Games", "Disposable Tableware"],
    # "Seasonal": ["Winter Gear", "Summer Essentials", "Rain Accessories", "Festive Decor", "Gifting"],
    # "Hobbies": ["Collectibles", "Model Building", "RC Toys", "Board Games", "Puzzles"],
    # "Travel Essentials": ["Travel Bottles", "Adapters", "Travel Pillows", "Organizers", "Luggage Tags"],
    # "Smart Wear": ["AR Glasses", "Smart Rings", "Smart Clothing", "Health Bands", "Tracking Chips"],
    # "Small Furniture": ["Side Tables", "Portable Chairs", "Shelves", "Stools", "Benches"],
    # "Home Storage": ["Storage Boxes", "Wardrobes", "Organizers", "Racks", "Shelving Units"],
    # "Audio Accessories": ["Cables", "DACs", "Audio Adapters", "Sound Dampening", "Microphone Stands"],
    # "Computer Components": ["Processors", "Motherboards", "RAM", "GPUs", "Storage Drives"],
    # "Mobile Accessories": ["Cables", "Chargers", "Phone Cases", "Screen Guards", "Holders"],
    # "Networking": ["Routers", "Modems", "Network Switches", "Mesh Systems", "Antennas"],
    # "3D Printing": ["3D Printers", "Filaments", "Resins", "Nozzles", "Printing Tools"],
    # "Drones": ["Camera Drones", "Racing Drones", "Mini Drones", "Drone Accessories", "Batteries"],
    # "Energy": ["Power Stations", "Solar Panels", "Inverters", "Batteries", "Chargers"],
    # "Bathroom": ["Bath Towels", "Bath Mats", "Shower Accessories", "Bathroom Storage", "Dispenser Sets"],
    # "Laundry": ["Laundry Bags", "Drying Racks", "Ironing Equipment", "Laundry Detergents", "Lint Removers"],
    # "Kitchen Storage": ["Jars", "Spice Racks", "Canisters", "Food Containers", "Bins"],
    # "Smart Kitchen": ["Smart Ovens", "Smart Kettles", "Smart Scales", "Smart Cooktops", "Smart Thermometers"],
    # "Emergency Supplies": ["Flashlights", "First Aid Kits", "Survival Gear", "Emergency Radios", "Thermal Blankets"],
    # "Fitness": ["Dumbbells", "Yoga Mats", "Resistance Bands", "Fitness Trackers", "Treadmills"],
    # "Cycling Gear": ["Bikes", "Helmets", "Gloves", "Lights", "Bike Accessories"],
    # "Camping": ["Tents", "Sleeping Bags", "Camp Stoves", "Camping Tools", "Lanterns"],
    # "Winter Sports": ["Ski Gear", "Snowboards", "Winter Apparel", "Snow Goggles", "Boots"],
    # "Water Sports": ["Kayaks", "Paddle Boards", "Swim Gear", "Diving Gear", "Water Safety"],
    # "Art & Design": ["Sketchbooks", "Markers", "Easels", "Canvases", " Brushes"],
    # "Photography Accessories": ["Tripods", "Lenses", "Lighting", "Stabilizers", "Filters"],
    # "Smart Health": ["Smart Scales", "Blood Pressure Monitors", "Smart Thermometers", "Sleep Trackers", "Health Scanners"],
    # "Air Quality": ["Air Purifiers", "Humidifiers", "Dehumidifiers", "Filters", "Sensors"],
    # "Home Safety": ["Smoke Alarms", "CO Detectors", "Fire Extinguishers", "Safety Kits", "Childproofing"],
    # "Baby Toys": ["Rattles", "Soft Toys", "Activity Centers", "Learning Toys", "Playmats"],
    # "Kids Fashion": ["T-Shirts", "Dresses", "Kids Shoes", "Winter Wear", "Accessories"],
    # "Stationery": ["Pens", "Notebooks", "Calendars", "Folders", "Markers"],
    # "Board Games": ["Strategy Games", "Family Games", "Party Games", "Card Games", "Tile Games"],
    # "Luxury": ["Designer Bags", "Premium Watches", "Gold Jewelry", "Silk Clothing", "Designer Shoes"],
    # "Ethnic Wear": ["Sarees", "Kurtas", "Ethnic Sets", "Dupattas", "Jewelry"],
    # "Smart Mobility": ["E-Scooters", "E-Bikes", "Hoverboards", "Charging Stations", "Safety Helmets"],
    # "Storage Media": ["Hard Drives", "SSDs", "Memory Cards", "USB Pen Drives", "NAS Drives"],
    # "Office Electronics": ["Projectors", "Conference Systems", "Telephones", "Shredders", "Binding Machines"],
    # "Industrial Safety": ["Safety Shoes", "Helmets", "Harnesses", "Gloves", "Reflective Gear"],
    # "Packaging Supplies": ["Cartons", "Tapes", "Bubble Wrap", "Labels", "Mailing Bags"],
    # "Event Supplies": ["Stage Lights", "Decor", "Sound Systems", "Banners", "AV Equipment"],
    # "Gift Items": ["Gift Sets", "Souvenirs", "Craft Gifts", "Keepsakes", "Personalized Gifts"],
    # "Green Living": ["Recycled Products", "Eco Bags", "Solar Chargers", "Bamboo Products", "Sustainable Decor"],
    # "Smart Office": ["Smart Whiteboards", "Smart Desks", "Smart Lighting", "Smart Locks", "Conference Assistants"],
    # "Automotive Tools": ["Jacks", "Wrenches", "Battery Chargers", "Car Diagnostic Tools", "Air Compressors"],
    # "Gardening Electronics": ["Robot Mowers", "Irrigation Controllers", "Plant Sensors", "Garden Lights", "Bug Zappers"],
    # "Wearable Cameras": ["Action Cameras", "Clip Cameras", "Body Cameras", "Sports Cameras", "Travel Cameras"],
    # "Home Entertainment": ["Mini Projectors", "Sound Systems", "Karaoke Machines", "Media Players", "Streaming Boxes"],
    # "Large Appliances": ["Dishwashers", "Freezers", "Water Heaters", "Ovens", "Cooktops"],
    # "Small Appliances": ["Toasters", "Grinders", "Irons", "Coffee Machines", "Kettles"],
    # "Luxury Appliances": ["Wine Coolers", "Premium Ovens", "Smart Fridges", "Ice Makers", "Smart Dishwashers"],
    # "Elder Care": ["Mobility Aids", "Health Monitors", "Orthopedic Products", "Comfort Wear", "Safety Supports"],
    # "Smart Lighting": ["Smart Bulbs", "Smart Panels", "Motion Lights", "RGB Strips", "Smart Lamps"],
    # "Smart Security": ["Video Doorbells", "Smart Cameras", "Motion Sensors", "Smart Alarms", "Pet Cameras"],
    # "Food Storage": ["Lunch Boxes", "Thermos", "Storage Bags", "Glass Containers", "Airtight Boxes"],
    # "Seasonal Clothing": ["Winter Jackets", "Summer Wear", "Raincoats", "Thermals", "Holiday Apparel"],
    # "Beverages": ["Soft Drinks", "Juices", "Energy Drinks", "Tea & Coffee", "Sports Drinks"],
    # "Snacks": ["Chips", "Nuts", "Chocolates", "Biscuits", "Bars"],
    # "Organic Foods": ["Organic Grains", "Organic Spices", "Organic Oils", "Organic Snacks", "Organic Tea"],
    # "Meat & Seafood": ["Fresh Chicken", "Fresh Fish", "Frozen Meats", "Marinated Meats", "Prawns"],
    # "Dairy": ["Milk", "Cheese", "Butter", "Yogurt", "Cream"],
    # "Frozen Foods": ["Frozen Snacks", "Frozen Veggies", "Ready Meals", "Frozen Desserts", "Frozen Breads"],
}
